version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "mindcard_teste1"
      POSTGRES_DB: mindcard
    ports:
      - "5436:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql

volumes:
  postgres18_data:
