version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "mindcard_teste1"
      POSTGRES_DB: mindcard
    ports:
      - "5436:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql
    networks:
      - mindcard-network

  redis:
    image: redis:7-alpine
    container_name: redis-mindcard
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - mindcard-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres18_data:
  redis_data:

networks:
  mindcard-network:
    driver: bridge
